### PR TITLE
Feature/password reset

### PR DESCRIPTION
**Pull request by adnan-i**

### CODE REVIEW

**Comment by adnan-i** [comment]
I'm not sure how you envisioned creating a proper url in reset token email, so I added the ability to pass the "resetUrl" in POST call to /users/password.
Let me know if there was another way.

**Comment by Kodemon** [comment]
I believe it was envisioned that the token is a small unique ID that you receive by email and put into a token prompt that takes you to the reset page from the front end. This way you can reset your password via any device without worrying about reset links.

The password reset hook would add a single letter to the token to imply what the token refers to `password-reset`, `phone-verification`, etc.

So lets say the token produces `762738`, the hook would then add `P` for example resulting in delivery of token `P762738`. The app would then read the token separating the first letter as the intended target, it sees the `P` and goes to the reset password form. Prompt the user to enter their new password and submit the password with the token `762738` and you are done.

So the reset flow would be.

user requests reset password > app opens up a modal or enters a new screen with a insert token prompt > user receives token by email and/or sms > inputs token > fills in new password and sends to api.

I don't think the hook has been setup for this yet but the email template does not currently make use of redirectUri and only provides the token to be input.

The token is also given a purpose when its stored and will only allow password reset requests to be used with the token provided etc.

**Comment by mattgi** [comment]
For a normal use case (i.e. user in App enters details, clicks next, then copies resulting email and pastes it in to current screen) a token on its own works.

To ensure we are on the same page:

For forgot password / password resets:
1. `app`/`web` anonymous POSTs to `/users/password`, passing in their phone or email as `identifier`.
2. `api` looks up user, generates/stores a token with a purpose of `password-reset`, and sends token via email and/or sms.
3. user enters token in `app`/`web` along with a new password and then PUTs to `/users/password` passing the token and new password.
4. `api` verifies token, accepts new password, and updates user's password.

For Email / Phone verification:
1. `app`/`web` anonymous user registers and supplies email/phone -OR- authenticated user updates their email/phone.
2. `api` accepts registration/update, (knows user), and then runs a hook, to identify that email/phone has been supplied, generates/stores a token with a purpose of `email/phone-verification`, and sends token via email and/or sms.
3. user enters token in `app`/`web` and makes a request to `/users/verify` passing the token and the relevant purpose (`email/phone-verification`).
4. `api` verifies token, updates user's details to set verifiedPhone/verifiedEmail and updates status from pending to active.

In both cases, step 3 is an unknown. The one thing we need to think about is how to get the user on to the applicable screen in the `app`/`web` to reset their password / verify their phone / verify their email when they are not already in the app. As we take it from a sync process to an async one we need to cater for this. This is compounded by the fact that a user should also be able to perform these same actions via the `app` or `web` (or a combination).

My thinking is that the token on its own works but there is no way in the App to know (or trigger) when to display the verification modal (other than already being in the App or a user providing some context when they open the App). The same is true for the web experience... unless they are sitting on the page, they will lose context and not know what URL they need to start a verification flow from.

This is where the Email/SMS information could include text along the lines of.

> Verify your xxxxxxxx by visiting WaiveCar on the __web__ or via our __mobile app__.

With links for each:
- https://example.com/password-reset?token=token
- ExampleAppName://password-reset?token=token
and
- https://example.com/verify?token=token&purpose=[email-verification | phone-verification]
- ExampleAppName://verify?token=token&purpose=[email-verification | phone-verification]

We can configure a URL scheme in the App via https://github.com/EddyVerbruggen/Custom-URL-scheme (already doing) which should allow us to provide a URL like the ExampleAppName one above in our SMS and Email notifications to get the App to open and navigate to a specific state. By also passing the token as a query string, we can even pre-fill it.

Are we all on the same page and do we agree on this approach?

**Comment by Kodemon** [comment]
I think step 3 could be solved neatly.

1. User clicks `reset password` and gets taken to a new screen asking them to enter identifier `sms/email`. After submitting this information they are taken to the reset form with fields `[ token, password, verify-password ]`.

2. If the user for some reason closes the page and aborts the process, we can a) link to the reset password page (where you enter your identifier). The difference is that if you are on the submit identifier page there is a link saying `Already have a token? Proceed to reset` taking them to the reset form.

This way you solve @mattgi nr. 3 and I think that its a intuitive approach. That means that from the area you pass your identifier for a request you can also choose to go directly to the form if you already have a token or closed the page by mistake.

So provide `redirectUri` for quick access to the wanted page if the user for some reason closed the web page or app and doesn't feel like accessing it through the interface.

**Comment by Kodemon** [comment]
Either way we are gonna want the ability for the front end to define a quick access redirectUri in the messages that is being sent out so I will merge this branch.

**Comment by mattgi** [comment]
I think for password reset it may work. But it won't for email/phone verifications and I feel like they are all closely related and should use a common ux

**Comment by Kodemon** [comment]
This is now currently a front end decision as how the tokens are delivered is done via the hooks. So we should consider this topic closed when it comes to the back end module and move the conversation into the project scope.

**Pull request merged**
